config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  scope '(:locale)', locale: /fr|cat/ do
    root to: 'pages#home'
    resources :musics
    resources :users
    resources :information, only: [:new, :create]
    resources :pictures
    resources :transports

    get '/wedding', to: 'pages#wedding'
    get '/contact', to: 'pages#contact'
    get '/tourism', to: 'pages#tourism'
    get '/present', to: 'pages#present'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :user
  validates :message, presence: true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
  validates :link, presence: true
  validates :name, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 10
end

app/models/transport.rb
class Transport < ApplicationRecord
  belongs_to :user
  validates :kind, presence: true
  validates :place_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_attachment :photo_avatar
  has_attachments :picture_name, maximum: 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email

  has_many :musics
  has_many :messages
  has_many :pictures
  has_many :transports


  FAMILLE = ["Ami de Jérémy","Amie de Jérémy", "Famille de Jérémy","Amiga de Blanca" ,"Amigo de Blanca", "Familiar de Blanca"]
  NATIONALITY = ["France", "España"]

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :famille])

    devise_parameter_sanitizer.permit(:account_update, keys: [:famille])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  skip_before_action :authenticate_user!
  def new
  #  @user = User.find(current_user)
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    @information.user_id = current_user.id
    if @information.save
      InformationMailer.creation_confirmation(@information).deliver_now
      InformationMailer.sending_confirmation(@information).deliver_now
      redirect_to contact_path
    else
      render :new
    end
  end

  private

  def information_params
    params.require(:information).permit(:subjet, :message, :type_message)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.includes(:user).all
  end

  def show
    @music = Music.find(params[:id])
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id
    if @music.save
      redirect_to musics_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private

  def music_params
    params.require(:music).permit(:name, :link, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]

  def home
  end

  def wedding
  end
  def contact
  end

  def maintenance
  end

  def transpot

    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:picture_name, photos: [])
  end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  def index
    @transports = Transport.all
  end

  def show
    @transport = Transport.find(params[:id])
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(transport_params)
    @transport.user_id = current_user.id
    if @transport.save
      redirect_to transports_path
    else
      render :new
    end
  end

  def edit
    @transport = Transport.find(params[:id])
  end

  def update
    @transport = Transport.find(params[:id])
    if @transport.update(transport_params)
      redirect_to transport_path
    else
      render :edit
    end
  end

  def destroy
    @transport = Transport.find(params[:id])
    @transport.destroy
    redirect_to transports_path
  end

  def transport_params
    params.require(:transport).permit(:depart, :return, :kind, :t_message, :place_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :nationality, :description, :photo_avatar, :photo_avatar2, :famille)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta property="og:title" content="Blanca-Jeremy">
    <meta property="og:url" content="<%= root_url %>">
    <meta property="og:type" content="website">
    <meta property="og:image" content="<%= image_url "minilogo.jpg"%>">
    <meta property="og:description" content="Blanca-Jeremy - We create this website for you">
    <meta property="og:site_name" content="Blanca-Jeremy"/>
    <link rel="icon" type="image/png" href="<%= image_url "minilogo.jpg"%>" />
    <title>Blanca-Jeremy - We have created this website for you</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/contact.html.erb
<br>
<div class="text-center">
  <%= link_to(t("send_information") , new_information_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<div class="wrapper-beige text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h3><%= t('contact_text') %></h3>
        <br>
        <i class="fa fa-user" style="color:#005971; font-size:30px; line-height:30px; vertical-align: middle;"> France</i>
        <br>
        <h3><%= t('contact_two_name') %></h3>
        <p><%= t('address_france') %></p>
        <p><%= t('contact_two_phone') %></p>
        <p><%= t('contact_email') %></p>
        <br>
        <i class="fa fa-user" style="color:#005971; font-size:30px; line-height:30px; vertical-align: middle;">  Espanya</i>
        <h3><%= t('contact_mum_blanca') %></h3>
        <p><%= t('address_spain') %></p>
        <p><%= t('contact_mum_blanca_telephone') %></p>
        <br>
        <i class="fa fa-user" style="color:#005971; font-size:30px; line-height:30px; vertical-align: middle;"> Martinique</i>
        <h3><%= t('contact_mum_jeremy') %></h3>
        <p><%= t('address_martinique') %></p>
        <p><%= t('contact_mum_jeremy_telephone') %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="responsive img-responsive">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="position: relative; top: 5vh; width: 100%; height: 90vh;overflow: hidden;">
    <!-- Indicators -->
    <ol class="carousel-indicators ">
    <br>
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner center-block" role="listbox" >
      <div class="item active">
        <%= image_tag "home1.JPG", width:"100%"%>
        <div class="carousel-caption">
          <h3>Madrid</h3>
          <p>Parque del Retiro</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home6.JPG", width:"100%" %>
        <div class="carousel-caption">
          <h3>Benidorm</h3>
          <p>Beach</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home2.JPG", width:"100%"%>
        <div class="carousel-caption">
          <h3>France</h3>
          <p>Château de Versailles</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home5.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Martinique</h3>
          <p>Demande en mariage</p>
        </div>
      </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev" >
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>
</div>
<!-- countdown starting -->
<div class="wrapper-beige">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-4 col-sm-12 ">
        <div class="text-center">
          <ul style="list-style: none; float: left; padding-top: 0.5vh;">
            <li>
              <h4><%= t('countdown') %> :</h4>
            </li>
            <li>
              <div id="getting-started" style="color: #408395; font-weight: stronger; font-size: 1.5em;"></div></div>
              <% content_for(:after_js) do %>
              <script type="text/javascript">
              $('#getting-started').countdown('2017/07/22', function(event) {
              $(this).html(event.strftime('%w <%= t('week') %>  %d <%= t('day') %> %H <%= t('hour') %> %M <%= t('minute') %> %S <%= t('second') %>'));
              });
              </script>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="text-center">
    <h4><%= t('annonce_title') %></h4>
    <br>
  </div>
  </div>

</div>
<!-- coutdown finished -->
<!-- grid of the website  -->
<!-- end of grid of website -->
<div class="container-fluid">
  <div class="row gutters">
    <!-- col -->
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to wedding_path do %>
          <%= image_tag "home4.JPG", alt: "ceremony", class: "responsive img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('title_ceremony') %></h3>
          <h6><%= t('text_ceremomy') %></h6>
        </div>
      </div>
    </div>
    <!-- end col -->
    <!-- col -->
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to musics_path do %>
          <%= image_tag "vignette2.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent ">
          <h3><%= t('title_music') %></h3>
          <h6><%= t('text_music') %></h6>
        </div>
      </div>
    </div>
    <!-- end col -->
    <!-- col -->
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to tourism_path do %>
          <%= image_tag "guadassuar2.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('title_tourism') %></h3>
          <h6><%= t('text_tourism') %></h6>
        </div>
      </div>
    </div>
    <!-- col -->
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to users_path do %>
          <%= image_tag "guadassuar1.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('invited') %></h3>
          <h6><%= t('invited_text') %></h6>
        </div>
      </div>
    </div>
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to transports_path do %>
          <%= image_tag "vignette5.JPG", alt: "ceremony", class: "responsive img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('transport_title') %></h3>
          <h6><%= t('add_transport') %></h6>
        </div>
      </div>
    </div>
    <!-- end col -->
    <!-- col -->
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to pictures_path do %>
          <%= image_tag "vignette6.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent ">
          <h3><%= t('gallery_title') %></h3>
          <h6><%= t('gallery_text') %></h6>
        </div>
      </div>
    </div>
    <!-- end col -->
    <!-- col -->
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to present_path do %>
          <%= image_tag "vignette8.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('present_title') %></h3>
          <h6><%= t('present_home') %></h6>
        </div>
      </div>
    </div>
    <!-- col -->
    <div class="col-xs-12  col-sm-6 col-md-6 col-lg-6 ">
      <div class="hovercontainer">
        <figure>
          <%= link_to contact_path do %>
          <%= image_tag "vignette7.JPG", alt: "ceremony", class: "img-responsive"%>
          <% end %>
        </figure>
        <div class="hovercontent">
          <h3><%= t('contact_title') %></h3>
          <h6><%= t('contact_text') %></h6>
        </div>
      </div>
  </div>

app/views/pages/maintenance.html.erb
<div class="banner_maintenance">
  <div class="banner-content">
    <h1>Le site est presque prêt, encore un peu de patience </h1>
    <p>Tu peux toujours nous contacter par mail au info@blanca-jeremy.com </p>
  </div>
</div>

app/views/pages/present.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="text-center">
      <br>
      <h1><%= t('present_title') %></h1>
    </div>
  </div>
</div>
</div>
<div class="wrapper-beige">
<div class="container">
  <p><%= t('present_text') %></p>
  <br>
  <h3 class="text-center"><%= t('Iban') %></h3>
</div>
</div>
<div class="container-fluid">
<div class="responsive img-responsive">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="position: relative; top: 5vh; width: 100%; height: 100vh;overflow: hidden;">
    <!-- Indicators -->
    <ol class="carousel-indicators ">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner center-block" role="listbox" >
      <div class="item active">
        <%= image_tag "photo_japan.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "photo_japan2.jpg", width:"100%" %>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "photo_japan3.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "photo_japan4.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "photo_japan5.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
      <div class="item">
        <%= image_tag "photo_japan6.jpg", width:"100%"%>
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p></p>
        </div>
      </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev" >
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>
  <br>
  <br>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon" >
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png"%>
  <% end %>

  <%= link_to root_path(:locale => 'cat'), class: "navbar-wagon-flag" do %>
  <%= image_tag "cat.png"%>
  <% end %>

  <%= link_to root_path(:locale => 'fr'), class: "navbar-wagon-flag" do %>
  <%= image_tag "fr.png"%>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->
    <%= link_to wedding_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('title_ceremony') %>
    <% end %>

    <!-- Text link -->
    <%= link_to users_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('invited') %>
    <% end %>

    <!-- Text link -->
    <%= link_to transports_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('transport_title') %>
    <% end %>

    <!-- Text link -->
    <%= link_to present_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('present_title') %>
    <% end %>

    <!-- Text link -->
    <%= link_to musics_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('title_music') %>
    <% end %>

    <!-- Text link -->
    <%= link_to tourism_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('title_tourism') %>
    <% end %>

    <%= link_to pictures_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('gallery_title') %>
    <% end %>

    <!-- Text link -->
    <%= link_to contact_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= t('contact_title') %>
    <% end %>
    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
      <i class="fa fa-search"></i>
      </button>
    </form> -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <!-- Notification -->
    <!--<%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <% end %> -->

    <!-- Profile picture and dropdown -->

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.photo_avatar? %>
        <%= cl_image_tag current_user.photo_avatar.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
        <%= image_tag "photo_avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: t('profile')) %>
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: t('log_out')) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login text link -->
    <%= link_to t(".sign_in", default: t('login')), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <!-- Button (call-to-action) -->
    <!-- <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to wedding_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('title_ceremony') %>
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('invited') %>
          <% end %>
        </li>
        <li>
          <%= link_to transports_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('transport_title') %>
          <% end %>
        </li>
        <li>
          <%= link_to present_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('present_title') %>
          <% end %>
        </li>
        <li>
          <%= link_to musics_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('title_music') %>
          <% end %>
        </li>
        <li>
          <%= link_to tourism_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('title_tourism') %>
          <% end %>
        </li>
        <li>
          <%= link_to pictures_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('gallery_title') %>
          <% end %>
        </li>
        <li>
          <%= link_to contact_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t('contact_title') %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>