config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  scope '(:locale)', locale: /fr|cat/ do
    root to: 'pages#home'
    resources :musics
    resources :users
    resources :information, only: [:new, :create]
    resources :pictures
    resources :transports

    get '/wedding', to: 'pages#wedding'
    get '/contact', to: 'pages#contact'
    get '/tourism', to: 'pages#tourism'
    get '/present', to: 'pages#present'
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :user
  validates :message, presence: true
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
  validates :link, presence: true
  validates :name, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 10
end

app/models/transport.rb
class Transport < ApplicationRecord
  belongs_to :user
  validates :kind, presence: true
  validates :place_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_attachment :photo_avatar
  has_attachments :picture_name, maximum: 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_email

  has_many :musics
  has_many :messages
  has_many :pictures
  has_many :transports


  FAMILLE = ["Ami de Jérémy","Amie de Jérémy", "Famille de Jérémy","Amiga de Blanca" ,"Amigo de Blanca", "Familiar de Blanca"]
  NATIONALITY = ["France", "España"]

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :famille])

    devise_parameter_sanitizer.permit(:account_update, keys: [:famille])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  skip_before_action :authenticate_user!
  def new
  #  @user = User.find(current_user)
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    @information.user_id = current_user.id
    if @information.save
      InformationMailer.creation_confirmation(@information).deliver_now
      InformationMailer.sending_confirmation(@information).deliver_now
      redirect_to contact_path
    else
      render :new
    end
  end

  private

  def information_params
    params.require(:information).permit(:subjet, :message, :type_message)
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def new
    @user = User.find(current_user)
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    @information.user_id = current_user.id
    if @information.save
      InformationMailer.creation_confirmation(@information).deliver_now
      redirect_to contact_path
    else
      render :new
    end
  end

  private

  def information_params
    params.require(:information).permit(:subject, :message, :type_message)
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.includes(:user).all
  end

  def show
    @music = Music.find(params[:id])
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id
    if @music.save
      redirect_to musics_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end

  private

  def music_params
    params.require(:music).permit(:name, :link, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]

  def home
  end

  def wedding
  end
  def contact
  end

  def maintenance
  end

  def transpot

    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:picture_name, photos: [])
  end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  def index
    @transports = Transport.all
  end

  def show
    @transport = Transport.find(params[:id])
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(transport_params)
    @transport.user_id = current_user.id
    if @transport.save
      redirect_to transports_path
    else
      render :new
    end
  end

  def edit
    @transport = Transport.find(params[:id])
  end

  def update
    @transport = Transport.find(params[:id])
    if @transport.update(transport_params)
      redirect_to transport_path
    else
      render :edit
    end
  end

  def destroy
    @transport = Transport.find(params[:id])
    @transport.destroy
    redirect_to transports_path
  end

  def transport_params
    params.require(:transport).permit(:depart, :return, :kind, :t_message, :place_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :nationality, :description, :photo_avatar, :photo_avatar2, :famille)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/information/create.html.erb
<h1>Information#create</h1>
<p>Find me in app/views/information/create.html.erb</p>

app/views/information/new.html.erb
<br>
<div class="text-center">
  <%= link_to(t("contact") , contact_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<div class="wrapper-beige">
  <h1 class="text-center" ><%= t('new_information_title') %></h1>
</div>
<br>
<div class="container" style="width: 70%; font-family: Quicksand; font-weight: lighter;">
  <div class="row">

    <%= simple_form_for(@information) do |f| %>
      <%= f.input :subjet ,label: t('sf_information_subject')%>
      <%= f.input :message ,label: t('sf_information_message')%>
      <br>
      <br class="text-center">
      <%= f.submit t('validate'), class: "hvr-grow btn btn-medium" %>
    <% end %>
    <br>
  </div>
</div>

app/views/informations/new.html.erb
<h1 class="text-center" ><%= t('new_information_title') %></h1>
<br>
<br>
<div class="container" style="width: 70%; font-family: Quicksand; font-weight: lighter;">
  <div class="row">
    <%= simple_form_for [@information] do |f| %>
    <%= f.input :type_message %>
    <%= f.input :subject %>
    <%= f.input :message %>
    <br>
    <br class="text-center">
    <%= f.submit "Valider" %>
    <% end %>
    <br>
  </div>
</div>

app/views/musics/create.html.erb
<h1>Musics#create</h1>
<p>Find me in app/views/musics/create.html.erb</p>

app/views/musics/destroy.html.erb
<h1>Musics#destroy</h1>
<p>Find me in app/views/musics/destroy.html.erb</p>

app/views/musics/edit.html.erb
<h1>Musics#edit</h1>
<p>Find me in app/views/musics/edit.html.erb</p>

app/views/musics/index.html.erb
<br>
<div class="text-center">
  <%= link_to(t("add_music"), new_music_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<div class="wrapper-beige">
  <div class="container" >
    <div class="row ">
      <div class="col-xs-12 col-sm-12 col-md-12 " style="padding-top: 2vh;">
        <div class="row">
          <div class="col-xs-12 col-sm-12col-md-12" style="position: relative; top: 3vh;">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12" style="margin-top: 3vh;">
                <div class="row">
                  <% @musics.each do |music| %>
                  <div class="hvr-float">
                    <div class="col-xs-12 col-sm-6 col-md-4 " style="margin-bottom: 30px;">
                      <div class="card " style="width: 350px; height: 350px;">
                        <div class="crop cropim" >
                          <iframe width="350" height="350" src="<%=music.link.gsub("watch?v=", "embed/")%>"  frameborder="0" allowfullscreen></iframe>
                        </div>
                      </a>
                      <div class="bottom-card">
                        <div class="name_user-white">
                         <% if music.user_id == current_user.id %>
                            <%= music.user.first_name %> <%= music.user.last_name %>
                            <%= link_to "", music_path(music.id), method: :delete, data: { confirm: t('comfirm_delete') }, class: "hvr-grow fa fa-trash-o "%>
                        <% else %>
                          <%= music.user.first_name %> <%= music.user.last_name %>
                        <% end %>
                        </div>
                        <div class="card-avatar">
                          <% if music.user.photo_avatar.present? %>
                              <%= cl_image_tag music.user.photo_avatar.path,:width => 150, :height => 150,
             :crop => :fill, :gravity => :faces %>
                            <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/musics/new.html.erb
<br>
<div class="text-center">
  <%= link_to(t("all_music"), musics_path, class: "hvr-grow btn btn-medium" )%>
  <br>
  <br>
</div>
<div class="wrapper-beige">
  <h2 class="text-center" ><%= t('new_music_title') %></h2>
</div>
<br>
<br>
<div class="container music">
  <div class="row">
    <%= simple_form_for [@music] do |f| %>
    <%= f.input :name ,label: t('sf_name_music') %>
    <%= f.input :link, label: t('sf_youtube_link') %>
    <% f.input :comment %>
    <br>
    <br class="text-center">
    <%= f.submit t('validate'), class: "hvr-grow btn btn-medium" %>
    <% end %>
    <br>
  </div>
</div>

app/views/musics/show.html.erb
<h1>Musics#show</h1>
<p>Find me in app/views/musics/show.html.erb</p>

app/views/musics/update.html.erb
<h1>Musics#update</h1>
<p>Find me in app/views/musics/update.html.erb</p>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/index.html.erb
<br>
<div class="text-center">
  <%= link_to(t("add_new_picture"), new_picture_path, class: "hvr-grow btn btn-medium") %>
  <br>

  <br>
</div>
<br>
<br>
<h6 class="text-center" ><%= t('display_picture') %> </h6>
<div class="wrapper-beige">
  <div class="container" >
    <div class="row ">
      <div class="col-xs-12 col-sm-12 col-md-12 " style="padding-top: 2vh;">
        <div class="row">
          <div class="col-xs-12 col-sm-12col-md-12" style="position: relative; top: 3vh;">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12" style="margin-top: 3vh;">
                <div class="row" id="lightGallery">
                  <% @pictures.each do  |picture| %>
                  <% picture.photos.each do |photo| %>
                  <div class="hvr-float">
                    <div class="col-xs-12 col-sm-6 col-md-4" style="margin-bottom: 30px;">
                      <div class="card" data-src="<%= photo.fullpath %>" style="width: 250px; height: 250px;">
                        <div class="crop cropim " >
                          <%= cl_image_tag photo.path, :width => 250, :height => 250, :crop => :fill %>
                        </div>
                        <div class="bottom-card">
                          <div class="name_user-white_2">
                          <% if picture.user_id == current_user.id %>
                          <%= picture.user.first_name %> <%= picture.user.last_name %>
                          <%= link_to "", picture_path(picture.id),  method: :delete, data: { confirm: "Are you sure?"}, class: "hvr-grow fa fa-trash-o " %>
                              <% else %>
                              <%= picture.user.first_name %> <%= picture.user.last_name %>
                            <% end %>
                          </div>
                          <div class="card-avatar">
                            <% if picture.user.photo_avatar.present? %>
                              <%= cl_image_tag picture.user.photo_avatar.path,:width => 150, :height => 150,
             :crop => :fill, :gravity => :faces %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<br>
<div class="text-center">
  <%= link_to(t("all_picture"), pictures_path, class: "hvr-grow btn btn-medium" )%>
  <br>
  <br>
</div>
<h1 class="text-center" ><%= t('new_picture') %></h1>
<h6 class="text-center" ><%= t('number_picture') %> </h6>
<br>
<br>
<div class="container" style="width: 70%; font-family: Quicksand; font-weight: lighter;">
  <div class="row">
    <%= simple_form_for [@picture] do |f| %>
    <%= f.input :picture_name ,label: t('sf_name_picture')%>
    <%= f.input :photos, as: :attachinary,label: t('sf_picture_name') %>
    <br>
    <br>
    <br class="text-center">
    <%= f.submit t('validate'), class: "btn btn-medium" %>
    <% end %>
    <br>
    <br>
  </div>
</div>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/transports/create.html.erb
<h1>Transports#create</h1>
<p>Find me in app/views/transports/create.html.erb</p>

app/views/transports/destroy.html.erb
<h1>Transports#destroy</h1>
<p>Find me in app/views/transports/destroy.html.erb</p>

app/views/transports/edit.html.erb
<br>
<div class="text-center">
  <%= link_to(t('all_transport'), transports_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<h1 class="text-center" ><%= t('modify_transport') %></h1>
<br>
<br>
<div class="container music">
  <div class="row">
    <%= simple_form_for [@transport] do |f| %>
      <%= f.input :depart, label:  t('depart') %>
      <%= f.input :return, label: t('return') %>
      <%= f.input :kind, label: t('type_transport') %>
      <%= f.input :place_number, label: t('place') %>
      <%= f.input :t_message, label: t('transport_message') %>
      <br>
      <br>
      <br class="text-center">
      <%= f.submit t('validate'), class: "btn btn-medium" %>
    <% end %>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/transports/index.html.erb
<br>
<div class="text-center">
  <%= link_to(t("add_transport") , new_transport_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<div class="wrapper-beige">
  <div class="container">
  <br>
    <br>
    <% @transports.each do  |transport| %>
    <div class="col-xs-12 col-sm-3 col-md-3 text-center">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom: 2vh;">
          <% if transport.user.photo_avatar? %>
            <%= cl_image_tag transport.user.photo_avatar.path,:style =>"border-radius: 50%; width: 150px; height: 150px; " %>
          <% else %>
          <%= image_tag "photo_avatar.jpg", :style =>"border-radius: 50%; width: 150px; height: 150px; " %>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12" style="font-family: Quicksand;font-size: 25px;">
        <h5><%= t('depart') %> : <%= transport.depart %></h5>
        <h5><%= t('retour') %> : <%= transport.depart %></h5>
        <h5><%= transport.kind %> : <%= transport.place_number %> <%= t('place') %></h5>
          <%=  transport.user.first_name %>
          <%=  transport.user.last_name %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom: 3vh;">
          <%= link_to(t('transport_message'), transport_path(transport.id), class: "hvr-grow ", :style =>"background: none; border: none; outline: none;text-decoration:none; color: #005971; font-size: 20px;font-family: 'Work Sans'; font-weight: regular;") %>
            <% if transport.user_id == current_user.id %>
               <%= link_to "", transport_path(transport.id), method: :delete, data: { confirm: t('comfirm_delete') }, class: "hvr-grow  fa fa-trash-o " %>
           <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>

app/views/transports/new.html.erb
<br>
<div class="text-center">
  <%= link_to(t('all_transport'), transports_path, class: "hvr-grow btn btn-medium") %>
  <br>
  <br>
</div>
<div class="wrapper-beige">
  <h1 class="text-center" ><%= t('new_transport') %></h1>
</div>
<br>
<div class="container" style="width: 70%; font-family: Quicksand; font-weight: lighter;">
  <div class="row">

    <%= simple_form_for(@transport) do |f| %>
      <%= f.input :depart, label:  t('depart')%>
      <%= f.input :return, label: t('return') %>
      <%= f.input :kind , label: t('type_transport')%>
      <%= f.input :place_number, label: t('place')%>
      <%= f.input :t_message, label: t('transport_message')  %>
      <br>
      <br class="text-center">
      <%= f.submit t('validate'),class: "btn btn-medium" %>
    <% end %>
    <br>
  </div>
</div>

app/views/transports/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 " style="padding-top: 5vh; ">
      <div>
        <div class="row ">
          <div class="col-xs-12 col-sm-12 col-md-12 text-center" >
            <div style="padding-bottom: 25px;">
              <% if @transport.user.photo_avatar? %>
              <%= cl_image_tag @transport.user.photo_avatar.path,:style =>"border-radius: 50%; width: 150px; height: 150px; " %>
              <% else %>
              <%= image_tag "photo_avatar.jpg", :style =>"border-radius: 50%; width: 150px; height: 150px; " %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row ">
          <div class="col-xs-12 col-sm-12 col-md-12 text-center"" >
            <div class="row ">
              <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <div style="display: inline-flex;justify-content: space-around;">
                  <div style="color:#408395 ;font-family: Quicksand; font-size: 35px;"><%= @transport.user.first_name %></div>
                  <div style="color:#408395;font-family: Quicksand; font-size: 35px;font-weight: bolder; padding-left: 10px"><%= @transport.user.last_name %></div>
                </div>
              </div>
              <div style="color:green;font-family: Quicksand; font-size: 25px; display: inline-flex;justify-content: space-around;">
                <%= "+ " + t('depart') %>
                <p style="padding-left: 25px;"><%= "+ " + t('return') %></p>
              </div>
              <br>
              <div style="color:grey;font-family: Quicksand; font-size: 25px; display: inline-flex;justify-content: space-around;">
                <%= "+ " +  @transport.depart %>
                <p style="padding-left: 25px;"><%= "+ " +  @transport.return%></p>
              </div>
              <br>
              <div style="color:grey;font-family: Quicksand; font-size: 25px; display: inline-flex;justify-content: space-around;">
                <%= "+ " +  @transport.kind %>
                <p style="padding-left: 25px;"><%= "+ " +  @transport.place_number %><%= t('place') %></p>
              </div>
            </div>
          </div>

          <div class="row ">
            <div class="col-xs-10 col-sm-10 col-md-10 text-justify col-xs-offset-1" style="font-family: Work Sans; font-size: 25px;color:grey; font-weight: bold">
              <%=  @transport.t_message %>
            </div>
          </div>
          <br>
          <div class="text-center">
          <% if @transport.user.id == current_user.id %>
            <%= link_to(t('modify_transport'), edit_transport_path(current_user), class: "hvr-grow btn btn-medium") %>
            <%= link_to(t('all_transport'), transports_path, class: "hvr-grow btn btn-medium") %>
            <%= link_to(t('contact_details'), user_path(@transport.user.id), class: "hvr-grow btn btn-blue") %>
            <% else %>
            <%= link_to(t('all_transport'), transports_path, class: "hvr-grow btn btn-medium") %>
            <%= link_to(t('contact_details'), user_path(@transport.user.id), class: "hvr-grow btn btn-blue") %>
            <% end %>
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transports/update.html.erb
<h1>Transports#update</h1>
<p>Find me in app/views/transports/update.html.erb</p>

app/views/users/_form.html.erb
<%= f.input :photo_avatar, as: :attachinary %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1 class="text-center" ><%= t('modify_profil') %></h1>
<br>
<br>
<div class="container music">
  <div class="row">
    <%= simple_form_for [@user] do |f| %>
    <%= f.input :first_name, label:  t('sf_first_name') %>
    <%= f.input :last_name, label: t('sf_last_name') %>
    <%= f.input :email, label: t('sf_email')%>
    <%= f.input :phone_number, label: t('sf_phone_number') %>
    <%= f.input :description, label: t('sf_description') %>
    <br>
    <%= f.select :nationality, User::NATIONALITY , label: t('nationality')%>
    <%= f.select :famille, User::FAMILLE %>
    <br>
    <br>
    <%= f.input :photo_avatar, as: :attachinary , label: t('sf_photo_avatar')%>
    <br>
    <br>
    <br class="text-center">
    <%= f.submit t('validate'), class: "hvr-grow btn btn-medium" %>
    <% end %>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/users/index.html.erb
<br>
<br>
<div class="container">
  <% @users.each_with_index do |user, index| %>
    <div class="col-xs-12 col-sm-3 col-md-3 text-center">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom: 2vh;">
          <% if user.photo_avatar? %>
            <%= cl_image_tag user.photo_avatar.path,:width => 150, :height => 150,
               :crop => :fill, :gravity => :faces, :radius => :max, :style =>"border-radius: 50%;" %>
          <% else %>
          <%= image_tag "photo_avatar.jpg", :style =>"border-radius: 50%; width: 150px; height: 150px; " %>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12" style="font-family: Quicksand;font-size: 25px; ">
          <%=  user.first_name %>
          <%=  user.last_name %>
          <br>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom: 3vh;">
          <%= link_to(t('more_details'), user_path(user.id), class: "hvr-grow ", :style =>"background: none; border: none; outline: none;text-decoration:none; color: #005971; font-size: 20px;font-family: 'Work Sans'; font-weight: regular;") %>
        </div>
      </div>
    </div>

    <% if (index + 1) % 4 == 0 %>
      <div class="clearfix"></div>
    <% end %>
  <% end %>
</div>
<br>
<br>
<br>
<br>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 " style="padding-top: 5vh; ">
      <div>
        <div class="row ">
          <div class="col-xs-12 col-sm-12 col-md-12 text-center" >
            <div style="padding-bottom: 25px;">
              <% if @user.photo_avatar? %>
              <%= cl_image_tag @user.photo_avatar.path, :width => 150, :height => 150,
             :crop => :fill, :gravity => :faces, :radius => :max, :style => "border-radius: 50%;" %>
              <% else %>
              <%= image_tag "photo_avatar.jpg", :style =>"border-radius: 50%; width: 150px; height: 150px; " %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row ">
          <div class="col-xs-12 col-sm-12 col-md-12 text-center"" >
            <div class="row ">
              <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <div style="display: inline-flex;justify-content: space-around;">
                  <div style="color:#408395 ;font-family: Quicksand; font-size: 35px;"><%= @user.first_name %></div>
                  <div style="color:#408395;font-family: Quicksand; font-size: 35px;font-weight: bolder; padding-left: 10px"><%= @user.last_name %></div>
                </div>
              </div>
              <div style="color:grey;font-family: Quicksand; font-size: 25px; display: inline-flex;justify-content: space-around;">
                <%= @user.nationality %>
                <p style="padding-left: 25px;"><%= @user.famille %></p>
              </div>
              <br>
              <div style="color:grey;font-family: Quicksand; font-size: 25px; display: inline-flex;justify-content: space-around;">
                <%= "+" + @user.email %>
                <p style="padding-left: 25px;"><%=  @user.phone_number %></p>
              </div>
            </div>
          </div>
          <div class="row ">
            <div class="col-xs-10 col-sm-10 col-md-10 text-justify col-xs-offset-1" style="font-family: Work Sans; font-size: 25px;color:grey; font-weight: bold">
              <%=  @user.description %>
            </div>
          </div>
          <br>
          <div class="text-center">
          <% if @user.id == current_user.id %>
            <%= link_to(t('edit_user'), edit_user_path(current_user), class: "hvr-grow btn btn-medium") %>
            <%= link_to(t('all_user'), users_path, class: "hvr-grow btn btn-medium") %>
            <% else %>
            <%= link_to(t('all_user'), users_path, class: "hvr-grow btn btn-medium") %>
            <% end %>
            <br>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>